// WashingtonEvent canonical types for Product One v0.1
export const EVENT_TYPES = {
  SESSION_START: 'SESSION_START',
  PAGE_VIEW: 'PAGE_VIEW',
  CTA_CLICK: 'CTA_CLICK',
  PLAYER_EVENT: 'PLAYER_EVENT',
  ONBOARDING_EVENT: 'ONBOARDING_EVENT'
}
